
data_path: H:/dev/mit/UNCWave/datasetfiles/FlatVel_A
model: 
    name: UNet
    unet_params:
        init_features: 32
        depth: 5
read_weights: null
batch_size: 8  #64
print_freq: 50 #500
max_epochs: 2 #20
es_epochs: 2 #4
seed: 42
valid_frac: 36
train_frac: 5
optimizer:
    lr: 0.0001
    weight_decay: 0.001
scheduler:
    params:
        factor: 0.316227766
        patience: 1
